### ISSUE TITLE
Tweaks de design possibles

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#49]
# Contexte

Pendant l'implémentation d'autres taches, on log ici les UX qu'on peut essayer d'améliorer plus tard

# Liste

## Page de comparaisons

- [ ] Avoir un overlay bleu en bas des tableaux si on a pas encore scroll au bout (cf Figma)
  - Difficile avec TableLite, car les div en overflow:hidden sont gérées par la lib
  
  <details<summary>Css utile</summary>
  
   ```css
   
  .table-wrapper {
    position: relative;
    overflow: hidden;

    .scroll-overlay {
      border-radius: 0px 0px 2px 2px;
      position: absolute;
      bottom: 1rem;
      right: 0;
      width: 100%;
      height: 50px;
      pointer-events: none;
  
      background-image: linear-gradient(transparent, #C3DDFD);
    }
  }
  ```
  </details>
  
- [ ] Empecher le scroll du body si on scroll en dehors de la modale ouverte
- [ ] Avoir la scrollbar de la modale de la meme couleur que les checkbox (et pas de la couleur d'accent du browser)

## Autres

- [x] Mettre tous les svg en `currentColor` pour bien les voir sur github & vscode
